config/routes.rb
# frozen_string_literal: true

# config/routes.rb
Rails.application.routes.draw do
  # User login stuff
  devise_for :users,
             controllers: {
               invitations: 'users/invitations',
               sessions: 'users/sessions',
               passwords: 'users/passwords'
             }

  # Static pages
  get 'get-in-touch', to: 'joins#new'
  post 'get-in-touch', to: 'joins#create'
  get 'privacy', to: 'pages#privacy'
  get 'find-placecal', to: 'pages#find_placecal'
  get 'our-story', to: 'pages#our_story'
  get 'terms-of-use', to: 'pages#terms_of_use'

  get 'community-groups', to: 'pages#community_groups'
  get 'metropolitan-areas', to: 'pages#metropolitan_areas'
  get 'vcses', to: 'pages#vcses'
  get 'housing-providers', to: 'pages#housing_providers'
  get 'social-prescribers', to: 'pages#social_prescribers'
  get 'culture-tourism', to: 'pages#culture_tourism'

  scope module: :admin, as: :admin, constraints: { subdomain: 'admin' } do
    resources :articles
    resources :calendars do
      member do
        post :import
      end
    end
    resources :collections
    resources :neighbourhoods
    resources :partners do
      collection do
        get :lookup_name
      end
      member do
        delete :clear_address
      end
    end
    resources :tags
    resources :sites
    resources :supporters
    resources :users do
      member do
        patch :update_profile
      end
    end
    get 'profile' => 'users#profile', as: :profile
    get 'jobs' => 'jobs#index', as: :jobs

    root 'pages#home'
  end

  constraints(Sites::Local) do
    get '/' => 'sites#index'
  end

  root 'pages#home'

  ymd = { year: /\d{4}/,
          month: /\d{1,2}/,
          day: /\d{1,2}/ }

  # Events
  resources :events, only: %i[index show]
  get '/events/:year/:month/:day' => 'events#index', constraints: ymd, as: :events_by_date

  # Partners
  resources :partners, only: %i[index show]
  get '/partners/:id/events' => 'partners#show'
  get '/partners/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places' => 'partners#index' # Removing separate Places view for now.
  get '/partners/:id/embed' => 'places#embed'

  # news
  resources :news, only: %i[index show]

  # Legacy routes from when some Partners were Places. Don't let Google down...
  get '/places/:id' => 'partners#show'
  get '/places/:id/events' => 'partners#show'
  get '/places/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places/:id/embed' => 'places#embed'

  # Collections
  resources :collections, only: %i[show]

  # Named routes
  get 'winter2017', to: 'collections#show', id: 1
  get 'winter2018', to: 'collections#show', id: 2

  get '/robots.txt' => 'pages#robots'

  post '/api/v1/graphql', to: 'graphql#execute'

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/api/v1/graphql' if Rails.env.development?
end

app/models/calendar.rb
# frozen_string_literal: true

# app/models/calendar.rb
class Calendar < ApplicationRecord
  include ActionView::Helpers::DateHelper
  include Validation
  extend Enumerize

  CALENDAR_REGEX = %r{\A(?:(?:(https?|webcal))://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:/[^\s]*)?\z}i.freeze

  self.inheritance_column = nil

  belongs_to :partner, optional: true
  belongs_to :place, class_name: 'Partner', optional: true
  has_many :events, dependent: :destroy

  validates :name, :partner, :source, presence: true
  validates :place, presence: { if: :requires_default_location?,
                                message: "can't be blank with this strategy" }
  validates :source, uniqueness: { message: 'calendar source already in use' },
                     format: { with: CALENDAR_REGEX, message: 'not a valid URL' }

  validate :check_source_reachable

  before_save :clear_status_on_source_change
  before_save :update_notice_count

  after_create :automatically_queue_calendar

  # Output the calendar's name when it's requested as a string
  alias_attribute :to_s, :name

  auto_strip_attributes :name, :source, :public_contact_name, :public_contact_email, :public_contact_phone

  # Defines the strategy this Calendar uses to assign events to locations.
  # @attr [Enumerable<Symbol>] :strategy
  enumerize(
    :strategy,
    in: %i[event_override event place room_number no_location online_only],
    default: :place,
    scope: true
  )

  ALLOWED_STATES = %i[idle in_queue in_worker error bad_source].freeze
  # State machine values
  enumerize(
    :calendar_state,
    in: ALLOWED_STATES,
    default: :idle
  )

  scope :that_appear_on_site, lambda { |site|
    site_partnership_tag_ids = site.tags.map(&:id)

    if site_partnership_tag_ids.length.positive?
      return Calendar.left_joins(partner: %i[address service_areas partnerships])
                     .where(
                       '(partner_tags.tag_id IN (:tags) AND '\
                       '(addresses.neighbourhood_id in (:neighbourhood_ids) OR '\
                       'service_areas.neighbourhood_id in (:neighbourhood_ids)))',
                       neighbourhood_ids: site.owned_neighbourhood_ids,
                       tags: site_partnership_tag_ids
                     )
                     .distinct
    else
      return Calendar.left_joins(partner: %i[address service_areas])
                     .left_joins(events: %i[address])
                     .where(
                       '(addresses.neighbourhood_id in (:neighbourhood_ids) OR '\
                       'service_areas.neighbourhood_id in (:neighbourhood_ids))',
                       neighbourhood_ids: site.owned_neighbourhood_ids
                     )
                     .distinct
    end
  }

  # We need a default location for some strategies
  def requires_default_location?
    %i[place room_number event_override].include? strategy.to_sym
  end

  # Output recent calendar import activity
  # This uses PaperTrail to get historical records of the Event models, including deletes
  # It does this to show a "event added" / "event removed" thing
  def recent_activity
    versions = PaperTrail::Version.with_item_keys('Event', event_ids).where('created_at >= ?', 2.weeks.ago)
    versions = versions.or(PaperTrail::Version.destroys
                                              .where("item_type = 'Event' AND object @> ? AND created_at >= ?",
                                                     { calendar_id: id }.to_json, 2.weeks.ago))

    versions = versions.order(created_at: :desc).group_by { |version| version.created_at.to_date }
  end

  # Get a count of all the events this week
  def events_this_week
    events.find_by_week(Time.now).count
  end

  # Who should be contacted about this calendar?
  def contact_information
    if public_contact_email
      [public_contact_email, public_contact_name]
    elsif partner&.public_email
      [partner.public_email, partner.public_name]
    elsif place&.public_email
      [place.public_email, place.public_name]
    else
      false
    end
  end

  #
  # calendar importer support methods
  #

  def self.import_up_to
    1.year.from_now
  end

  # internal model function
  def update_notice_count
    self.notice_count = (notices || []).count if notices_changed?
  end

  def automatically_queue_calendar
    queue_for_import! false, DateTime.now
  end

  #
  # calendar state mutators
  #

  # push calendar into queue
  #
  # @param force_import [Boolean]
  #   boolean to bypass checks on redundant imports
  # @param from_date [String]
  #   date to use as the start point
  #
  # @return nothing
  def queue_for_import!(force_import, from_date = Time.now)
    transaction do
      return if is_busy?

      Calendar.record_timestamps = false
      update! calendar_state: :in_queue, notices: nil

      CalendarImporterJob.perform_later id, from_date, force_import

    ensure
      Calendar.record_timestamps = true
    end
  end

  # flag calendar record that importing has started
  #
  # @return nothing
  def flag_start_import_job!
    transaction do
      return unless calendar_state.in_queue?

      Calendar.record_timestamps = false
      update! calendar_state: :in_worker, notices: nil

    ensure
      Calendar.record_timestamps = true
    end
  end

  # Flag calendar record that importing has completed successfully
  # and store a timestamp, checksum and notices
  #
  # @param notices [Array]
  #   array of strings of messages generated by the importer
  #   during its normal operation
  # @param checksum [integer]
  #   integer checksum of retrieved source payload
  # @return nothing
  def flag_complete_import_job!(notices, importer_used)
    transaction do
      return unless calendar_state.in_worker?

      Calendar.record_timestamps = false

      update!(
        calendar_state: :idle,
        notices: notices,
        last_import_at: DateTime.current,
        critical_error: nil,
        importer_used: importer_used
      )

    ensure
      Calendar.record_timestamps = true
    end
  end

  def flag_checksum_change!(checksum)
    transaction do
      Calendar.record_timestamps = false
      update!(
        last_checksum: checksum,
        checksum_updated_at: DateTime.current
      )
    ensure
      Calendar.record_timestamps = true
    end
  end

  def flag_bad_source!(problem)
    transaction do
      return unless calendar_state.in_worker?

      # we need the state to be valid so we discard everything
      # before saving error
      reload

      Calendar.record_timestamps = false
      self.calendar_state = :bad_source
      self.critical_error = problem
      save!

    ensure
      Calendar.record_timestamps = true
    end
  end

  # Flag calendar record a problem has occurred and that all
  # future processing will cease until the user resets this calendar
  # elsewhere
  # NOTE: this reloads the model object so if you want to keep any
  # built up state then this WILL clobber that.
  #
  # @param problem [String]
  #   string describing the basic problem the importer failed on
  #
  # @eturn
  #   nothing
  def flag_error_import_job!(problem)
    transaction do
      return unless calendar_state.in_worker?

      # we need the state to be valid so we discard everything
      # before saving error
      reload

      Calendar.record_timestamps = false
      self.calendar_state = :error
      self.critical_error = problem
      save validate: false

    ensure
      Calendar.record_timestamps = true
    end
  end

  def state_colour
    case calendar_state
    when 'in_queue'
      'primary'
    when 'in_worker'
      'success'
    when 'error'
      'danger'
    else
      'info'
    end
  end

  # is calendar being worked on by our backend?
  def is_busy?
    calendar_state.in_queue? || calendar_state.in_worker?
  end

  # is a user allowed to requeue a calendar for import?
  def can_be_requeued?
    calendar_state.idle? || calendar_state.bad_source?
  end

  private

  # called for validation
  def check_source_reachable
    return unless source_changed?
    return if errors[:source].any?

    # The calendar importer will raise an exception if the source
    #   URL has a problem
    CalendarImporter::CalendarImporter.new(self)
  rescue CalendarImporter::Exceptions::InaccessibleFeed => e
    errors.add :source, "The source URL returned an invalid code (#{e})"
  rescue CalendarImporter::Exceptions::UnsupportedFeed => e
    errors.add :source, 'Unable to autodetect calendar format, please pick an option from the list below'
  end

  def clear_status_on_source_change
    return unless source_changed?

    self.critical_error = nil
    self.notices = nil
    self.last_import_at = nil
  end
end

app/controllers/admin/calendars_controller.rb
# frozen_string_literal: true

# app/controllers/admin/calendars_controller.rb
module Admin
  class CalendarsController < Admin::ApplicationController
    before_action :set_calendar, only: %i[show edit update destroy import]
    before_action :preselect_partner, only: %i[new create]

    def index
      @calendars = policy_scope(Calendar).order(updated_at: :desc).order(:name)
      authorize Calendar

      respond_to do |format|
        format.html
        format.json do
          render json: CalendarDatatable.new(
            params,
            view_context: view_context,
            calendars: @calendars
          )
        end
      end
    end

    def new
      @calendar = Calendar.new
      authorize @calendar
    end

    def edit
      authorize @calendar
      @versions = @calendar.recent_activity
      @partner = @calendar.partner
    end

    def show
      authorize @calendar
    end

    def create
      @calendar = Calendar.new(calendar_params)
      authorize @calendar

      if @calendar.save
        redirect_to edit_admin_calendar_path(@calendar)
        flash[:success] = 'New calendar created and queued for importing. Please check back in a few minutes.'
      else
        flash.now[:danger] = 'Calendar did not save'
        render 'new', status: :unprocessable_entity
      end
    end

    def update
      if @calendar.update(calendar_params)
        flash[:success] = 'Calendar successfully updated'
        redirect_to edit_admin_calendar_path(@calendar)
      else
        flash.now[:danger] = 'Calendar did not save'
        render 'edit', status: :unprocessable_entity
      end
    end

    def destroy
      authorize @calendar
      @calendar.destroy
      respond_to do |format|
        format.html do
          flash[:success] = 'Calendar was successfully deleted.'
          redirect_to admin_calendars_url
        end

        format.json { head :no_content }
      end
    end

    def import
      force_import = true
      @calendar.queue_for_import! force_import

      flash[:success] = 'Calendar added to the import queue'
      redirect_to edit_admin_calendar_path(@calendar)
    end

    private

    def preselect_partner
      return if params[:partner_id].blank?

      # TODO: better calendar-to-user scoping
      @partner = current_user.partners.where(id: params[:partner_id]).first
    end

    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def calendar_params
      params.require(:calendar).permit(
        :id,
        :name,
        :source,
        :strategy,
        :address_id,
        :strategy,
        :partner_id,
        :place_id,
        :importer_mode,
        :public_contact_name,
        :public_contact_phone,
        :public_contact_email,
        :checksum_updated_at
      )
    end
  end
end

app/helpers/calendars_helper.rb
# frozen_string_literal: true

module CalendarsHelper
  def options_for_organiser
    org_opts = policy_scope(Partner)
               .order(:name)
               .collect { |opt| [opt.name, opt.id] }

    # [{ name: '', id: ''}] + org_opts
    [['(No Partner)', '', { disabled: true }]] + org_opts
  end

  def options_for_location
    policy_scope(Partner)
      .with_address
      .order(:name)
  end

  def options_for_importer
    CalendarImporter::CalendarImporter::PARSERS
      .dup
      .keep_if { |parser| parser::PUBLIC }
      .map { |parser| [parser::NAME, parser::KEY] }
      .prepend(['(Auto detect)', 'auto'])
  end

  def summarize_dates(dates)
    if dates.length > 3
      sorted = dates.sort
      "#{dates.count} dates between #{sorted.first.strftime('%a, %b %e, %Y')} and #{sorted.last.strftime('%a, %b %e, %Y')}"
    else
      dates.map { |date| date.strftime('%b %e %Y (%a)') }.join(', ')
    end
  end

  def display_time_since(date)
    if DateTime.current.to_date == date.to_date
      'Today'
    else
      "#{(Date.current - date).to_i} Days Ago"
    end
  end

  def strategy_label(val)
    case val.second
    when 'event'
      '<strong>Event</strong>: ' \
      'Use the address from each event. '\
      'If an address is invalid or it doesn\'t have one, the event will import with no location.'.html_safe
    when 'place'
      '<strong>Default location</strong>: ' \
      'Always use the calendar\'s default location.'.html_safe
    when 'room_number'
      '<strong>Room number</strong>: ' \
      'Get a room number from the event\'s address, '\
      'and overwrite the rest of the address with the calendar\'s default location.'.html_safe
    when 'event_override'
      '<strong>Event where possible</strong>: ' \
      'Use the address from each event. '\
      'If the address is invalid or it doesn\'t have one, use the calendar\'s default location.'.html_safe
    when 'no_location'
      '<strong>No location</strong>: ' \
      'Discard any address information.'.html_safe
    when 'online_only'
      '<strong>Online only</strong>: ' \
      'Discard any address information but retain web links.'.html_safe
    else
      val
    end
  end

  def calendar_import_sources
    parsers = CalendarImporter::CalendarImporter::PARSERS
              .dup
              .keep_if { |parser| parser::PUBLIC }
              .sort { |a, b| a::NAME <=> b::NAME }

    parsers.each do |parser|
      yield parser::NAME, parser::DOMAINS
    end
  end

  def calendar_last_imported(calendar)
    if calendar&.last_import_at
      "Last imported #{time_ago_in_words(calendar.last_import_at)} ago"
    else
      'Never imported'
    end
  end
end

app/views/admin/calendars/_form.html.erb
<p>
  <%= link_to "View this calendar",
      admin_calendar_path(@calendar.id),
      class: "btn btn-sm btn-primary" unless @calendar.new_record? %>
</p>

<%= render('importer_overview', calendar: @calendar) %>
<hr>

<div id="js-calendar-form">
  <%= simple_form_for [:admin, @calendar] do |f| %>
    <div class="row">
      <div class="col-md-6">
        <h3>Details</h3>

        <%= f.association :partner,
                          label: 'Partner Organiser',
                          collection: options_for_organiser,
                          selected: (@partner&.id || @calendar.partner_id).to_s,
                          input_html: { class: 'form-control', data: {controller: "select2"} },
                          hint: 'Which group organises these events?' %>

        <%= f.input :name, hint: 'A simple description to help rememember what this calendar is' %>
        <%= f.input :source, label: 'URL', placeholder: 'https://your-domain.com/events.ics', hint: "The source URL for your calendar feed. See the #{link_to 'PlaceCal Handbook', 'https://handbook.placecal.org/admin-handbook'} if you need help.".html_safe %>
        <%= f.input :importer_mode,
          collection: options_for_importer,
          default: 'auto',
          input_html: { class: 'form-control' } %>


        <div class='hint'>
          <p>
            Calendar source URLs that PlaceCal currently supports are:
          </p>
          <ul>
          <% calendar_import_sources do |name, domains| -%>
            <li><%= name %> (<%= domains.join(', ') %>)</li>
          <% end -%>
          </ul>
        </div>
        <% if @calendar.importer_used.present? -%>
          <p>The calendar was last imported using the <%= @calendar.importer_used %> importer.</p>
        <% end -%>

      </div>
      <div class="col-md-6">
        <h3>Location</h3>
        <div v-if="locationVisible">
          <%= f.association :place,
                            label: 'Default location',
                            collection: options_for_location,
                            input_html: { class: 'form-control', data: {controller: "select2"} } %>
        </div>
        <%= f.input :strategy,
                    as: :radio_buttons,
                    label: 'Where should location information for this calendar come from?',
                    label_method: ->(val){strategy_label(val)},
                    input_html: { 'v-model': 'strategy', 'v-on:change': "updateLocation" } %>
      </div>
    </div>

    <hr>
    
    <h3 class="mt-5">Public Contact Information</h3>
    <div class="row">
      <div class="col-md-6">
	<p>
	  This information is used on the <em>public</em>
	  event listing pages in the "Problem with this listing? Let us know."
	  contact link at the bottom of the show event page.
	</p>

	<%= f.input :public_contact_name %>
	<%= f.input :public_contact_email %>
	<%= f.input :public_contact_phone %>
      </div>
    </div>

    <hr>
    <%= f.button :submit, class: "btn btn-primary mr-3" %>
    <% unless @calendar.new_record? %>
      <%= link_to "Destroy Calendar", admin_calendar_path(@calendar), method: :delete, class: "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/admin/calendars/_importer_overview.html.erb
<% unless calendar.new_record? %>
  <% retry_button = nil %>
  <hr>
  <h3>Import status</h3>

  <% if calendar.checksum_updated_at.present? && calendar.last_import_at.present? %>
    <% if calendar.checksum_updated_at < 6.month.ago || calendar.last_import_at < 6.month.ago %>
      <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Potential stale calender</h4>
        <p>Is this calender still active? It has not been updated in over 6 months</p>
      </div>
    <% end %>
  <% end %>

  <% if calendar.calendar_state.idle? %>
    <% retry_button = :idle %>
    <h4><span class="badge badge-success">success</span></h4>
  <% end %>

  <% if calendar.calendar_state.in_queue? || calendar.calendar_state.in_worker? %>
    <h4><span class="badge badge-primary">loading</span></h4>
    <p>Please check back in a few minutes</p>
  <% end %>

  <% if calendar.calendar_state.error? || calendar.calendar_state.bad_source? %>
    <% retry_button = :error %>

    <h4><span class="badge badge-danger">error</span></h4>

    <div class="alert alert-warning" role="alert">
      Error: <%= calendar.critical_error %>
    </div>
  <% end %>


  <% if calendar.checksum_updated_at.present? %>
    <p>
    <strong>Source data last changed <%= time_ago_in_words(calendar.checksum_updated_at) %> ago</strong> (<%= calendar.checksum_updated_at %>)
    </p>
  <% end %>

  <% if calendar.last_import_at.present? %>
    <p>
    <strong>Last import ran <%= time_ago_in_words(calendar.last_import_at) %> ago</strong> (<%= calendar.last_import_at %>)
    </p>
  <% end %>

  <% if calendar.notices.present? %>
    <% retry_button = :error %>

    <h4>Notices</h4>
    <p>The following events could not be imported due to invalid data: </p>

    <ul id="calendar-notices">
      <% calendar.notices.tally.each do |text, count| %>
        <li><%= text %> <% if count > 1 %>(<%= count %> times)<% end %></li>
      <% end %>
    </ul>
    <p>Please check your calendar is set up correctly and try again.</p>
  <% end %>

  <% if retry_button %>
    <%= simple_form_for :import, { url: import_admin_calendar_path(calendar) } do |f| %>
      <% if retry_button == :idle %>
        <%= f.submit 'Re-import now', class: 'btn btn-primary' %>
      <% elsif retry_button == :error %>
        <%= f.submit 'Retry', class: 'btn btn-danger' %>
      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/admin/calendars/edit.html.erb
<script>
  const currentInfo = <%= @calendar.to_json.html_safe %>
</script>

<%= render_component "admin_edit", model: :calendar, title: @calendar.name %>

app/views/admin/calendars/index.html.erb
<script>
var columns = [
    {"data": "name"},
    {"data": "partner"},
    {"data": "notice_count"},
    {"data": "events"},
    {"data": "state"},
    {"data": "last_import_at",
     "render": function (data, type, row) {
         date = JSON.parse(data.replace(/&quot;/g, '"'));
         return (type == "display") ? date.strtime : date.unixtime;
     }
    },
    {"data": "checksum_updated_at",
     "render": function (data, type, row) {
         date = JSON.parse(data.replace(/&quot;/g, '"'));
         return (type == "display") ? date.strtime : date.unixtime;
     }
    },
  ]
</script>

<%# A weird bug in the datatables template means that we have to apply the margin for each link, rather than for the container span. %>
<%= render partial: 'layouts/admin/datatable', locals: {
    title: 'Calendars',
    model: :calendars,
    column_titles: ['Name', 'Partners', 'Notices', 'Events', 'Status', 'Last imported', 'Source updated'],
    columns: %i[name partner notice_count events calendar_state last_import_at checksum_updated_at],
    data: @calendars,
    source: admin_calendars_path(format: :json),
    new_link: new_admin_calendar_path
  }
%>

app/views/admin/calendars/new.html.erb
<% content_for :title do %>New Calendar<% end %>

<%= render_component "admin_new", model: :calendar %>

app/views/admin/calendars/select_page.html.erb
<h2>Select the page you would like to import events from</h2>

<ul>
  <%- @pages.each do |page| %>
    <li>
      <%- if !page['has_access'] %>
        <%= page['name'] %> <small class="red">* You do not have the correct permissions for add this page. Please ensure you are both a Page Admin for this page</small>
      <%- elsif params[:calendar_id].present? %>
        <%= link_to page['name'], edit_admin_calendar_path(params[:calendar_id], page_name: page['name'], page_link: page['link'], page_id: page['id']) %>
      <% else %>
        <%= link_to page['name'], new_admin_calendar_path(page_name: page['name'], page_link: page['link'], page_id: page['id']) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/calendars/show.html.erb
<h1><%= @calendar.name %></h1>
<p><%= link_to "Edit this calendar", edit_admin_calendar_path(@calendar.id), class: "btn btn-primary btn-sm" %></p>

<%= render 'importer_overview', calendar: @calendar %>
<hr>

<p>Published by <%= link_to @calendar.partner, edit_admin_partner_path(@calendar.partner) %>. Using <%= content_tag :tt, @calendar.strategy %> strategy to import <%= content_tag :tt, @calendar.events.count %> events. <%= calendar_last_imported(@calendar) %>.</p>

<p>
  <% if @calendar.place %>
    This calendar's default location is <%= link_to @calendar.place, edit_admin_partner_path(@calendar.place) %>.
  <% else %>
    This calendar does not have a default location set.
  <% end %>
</p>


<div class="row">
  <div class="col-md-6">
    <h2>Events</h2>

    <h3>Upcoming</h3>
    <ol class="pl-3">
      <% @calendar.events.upcoming.each do |event| %>
        <li><%= content_tag :strong, event.date_year %>. <%= event.summary %></li>
      <% end %>
    </ol>

    <h3>Past</h3>
    <ol class="pl-3">
      <% @calendar.events.past.limit(50).each do |event| %>
        <li><%= content_tag :strong, event.date_year %>. <%= event.summary %></li>
      <% end %>
    </ol>
  </div>
</div>