config/routes.rb
# frozen_string_literal: true

# config/routes.rb
Rails.application.routes.draw do
  # User login stuff
  devise_for :users,
             controllers: {
               invitations: 'users/invitations',
               sessions: 'users/sessions',
               passwords: 'users/passwords'
             }

  # Static pages
  get 'get-in-touch', to: 'joins#new'
  post 'get-in-touch', to: 'joins#create'
  get 'privacy', to: 'pages#privacy'
  get 'find-placecal', to: 'pages#find_placecal'
  get 'our-story', to: 'pages#our_story'
  get 'terms-of-use', to: 'pages#terms_of_use'

  get 'community-groups', to: 'pages#community_groups'
  get 'metropolitan-areas', to: 'pages#metropolitan_areas'
  get 'vcses', to: 'pages#vcses'
  get 'housing-providers', to: 'pages#housing_providers'
  get 'social-prescribers', to: 'pages#social_prescribers'
  get 'culture-tourism', to: 'pages#culture_tourism'

  scope module: :admin, as: :admin, constraints: { subdomain: 'admin' } do
    resources :articles
    resources :calendars do
      member do
        post :import
      end
    end
    resources :collections
    resources :neighbourhoods
    resources :partners do
      collection do
        get :lookup_name
      end
      member do
        delete :clear_address
      end
    end
    resources :tags
    resources :sites
    resources :supporters
    resources :users do
      member do
        patch :update_profile
      end
    end
    get 'profile' => 'users#profile', as: :profile
    get 'jobs' => 'jobs#index', as: :jobs

    root 'pages#home'
  end

  constraints(Sites::Local) do
    get '/' => 'sites#index'
  end

  root 'pages#home'

  ymd = { year: /\d{4}/,
          month: /\d{1,2}/,
          day: /\d{1,2}/ }

  # Events
  resources :events, only: %i[index show]
  get '/events/:year/:month/:day' => 'events#index', constraints: ymd, as: :events_by_date

  # Partners
  resources :partners, only: %i[index show]
  get '/partners/:id/events' => 'partners#show'
  get '/partners/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places' => 'partners#index' # Removing separate Places view for now.
  get '/partners/:id/embed' => 'places#embed'

  # news
  resources :news, only: %i[index show]

  # Legacy routes from when some Partners were Places. Don't let Google down...
  get '/places/:id' => 'partners#show'
  get '/places/:id/events' => 'partners#show'
  get '/places/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places/:id/embed' => 'places#embed'

  # Collections
  resources :collections, only: %i[show]

  # Named routes
  get 'winter2017', to: 'collections#show', id: 1
  get 'winter2018', to: 'collections#show', id: 2

  get '/robots.txt' => 'pages#robots'

  post '/api/v1/graphql', to: 'graphql#execute'

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/api/v1/graphql' if Rails.env.development?
end

app/views/layouts/admin/_admin_navigation.html.erb
<ul class="nav flex-column">

  <%= admin_nav_link('Dashboard', admin_root_path, 'home') %>
  <%= admin_nav_link('Partners', admin_partners_path, 'map') if policy(Partner).index? %>
  <%= admin_nav_link('Calendars', admin_calendars_path, 'calendar') if policy(Calendar).index? %>

  <% if has_any_global_admin_links? -%>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Global admin</span>
    </h6>
    <%= admin_nav_link('Users', admin_users_path, 'users') if policy(User).index? %>
    <%= admin_nav_link('Sites', admin_sites_path, 'sitemap') if policy(Site).index? %>
    <%= admin_nav_link('Neighbourhoods', admin_neighbourhoods_path, 'location-arrow') if policy(Neighbourhood).index? %>
    <%= admin_nav_link('Tags', admin_tags_path, 'tags') if policy(Tag).index? %>
  <% end -%>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Get support</span>
    </h6>
    <%= admin_nav_link('Handbook', 'https://handbook.placecal.org/', 'book')%>
    <%= admin_nav_link('Discord', 'http://discord.gfsc.studio/', 'comment')%>
    <%= admin_nav_link('Report a bug', 'https://github.com/geeksforsocialchange/PlaceCal/issues/new?assignees=&labels=&template=bug_report.md', 'bug')%>
    <li class="nav-item"><span class="nav-link"><i class="fa fa-envelope feather"></i> support@placecal.org</span></li>

  <% if policy(Collection).index? || policy(Supporter).index? %>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>In development</span>
    </h6>
    <%= admin_nav_link('Articles', admin_articles_path, 'newspaper-o') if policy(Article).index? %>
    <%= admin_nav_link('Collections', admin_collections_path, 'list') if policy(Collection).index? %>
    <%= admin_nav_link('Supporters', admin_supporters_path, 'credit-card') if policy(Supporter).index? %>
    <%= admin_nav_link('Import status', admin_jobs_path, 'gear') if current_user.root? %>
  <% end %>
</ul>

<br><br>

<p class="small text-info ml-3">
<% build = ENV['GIT_REV'] ? ENV['GIT_REV'][0,7] : 'development' %>
<i class="fa fa-git"></i> Build: <tt><%= link_to build, "https://github.com/geeksforsocialchange/PlaceCal/commit/#{build}" %></tt>

</p>

app/views/layouts/admin/_admin_topbar.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to 'PlaceCal', admin_root_path, class: "navbar-brand col-sm-3 col-md-2 mr-0" %>
  <ul class="navbar-nav flex-row px-3">
    <li class="nav-item text-nowrap mr-4">
      <%= link_to "<i class='fa fa-user'></i> #{@current_user&.email} #{"👑" if @current_user&.role == :root}".html_safe, admin_profile_path, class: 'nav-link'  %>
    </li>
    <li class="nav-item text-nowrap">
      <%= button_to destroy_user_session_path, method: :delete, class: 'btn nav-link', form: { data: { turbo: 'false' } } do %>
      <i class='fa fa-sign-out'></i> Sign out
    <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/admin/_datatable.html.erb
<% content_for :title do %><%= title %><% end %>

<h1 class="page-header"><%= title %></h1>

<%- model_name = model.to_s.chop.humanize %>

<span>
  <%- if policy(model_name.constantize).create? && defined?(new_link) %>
    <%= link_to "Add New #{model_name}", new_link, data: { turbo: false }, class: "btn btn-primary mb-3" %>
  <% end %>

  <%# are these used at all?
    # <.% if defined?(additional_links) %.>
    # <.% additional_links.each do |link| %.>
    #   <.%= sanitize link %.>
    # <.% end %.>
    # <.% end %.>
  %>
</span>

<table class="table table-striped" id="datatable" data-source="<%= source %>">
  <thead>
    <tr>
      <% column_titles.each do |title| %>
        <th><%= title %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%# While testing, it might be easier to delete the following block %>
    <% data&.each do |record| %>
      <tr>
        <% record.slice(columns).each do |key, value| %>
          <td>
            <%= value %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{yield(:title)} | " if content_for?(:title) %>PlaceCal Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'admin', 'https://fonts.googleapis.com/css?family=Raleway:500,700,800|Trocchi', media: 'all', 'data-turbo-track': 'reload' %>
    
    <%= javascript_include_tag 'admin', 'data-turbo-track': 'reload', defer: true %>
    <%= stylesheet_link_tag 'admin', 'data-turbo-track': 'reload' %>

    <%= render "layouts/meta" %>
  </head>

  <body>
    <%= render "layouts/admin/admin_topbar" %>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <%= render "layouts/admin/admin_navigation" %>
          </div>
        </nav>
        <main role="main" class="col-md-9 mt-3 ml-sm-auto col-lg-10 px-4">
          <%= render(AdminFlashComponent.new(flash: flash)) %>
          <%= yield %>

          <% if Rails.env.development? %>
            <div class="text-monospace text-muted mt-5">
              <%= debug(params) %>
              <%# console %>
            </div>
          <% end %>
        </main>
      </div>
    </div>
  </body>
</html>