config/routes.rb
# frozen_string_literal: true

# config/routes.rb
Rails.application.routes.draw do
  # User login stuff
  devise_for :users,
             controllers: {
               invitations: 'users/invitations',
               sessions: 'users/sessions',
               passwords: 'users/passwords'
             }

  # Static pages
  get 'get-in-touch', to: 'joins#new'
  post 'get-in-touch', to: 'joins#create'
  get 'privacy', to: 'pages#privacy'
  get 'find-placecal', to: 'pages#find_placecal'
  get 'our-story', to: 'pages#our_story'
  get 'terms-of-use', to: 'pages#terms_of_use'

  get 'community-groups', to: 'pages#community_groups'
  get 'metropolitan-areas', to: 'pages#metropolitan_areas'
  get 'vcses', to: 'pages#vcses'
  get 'housing-providers', to: 'pages#housing_providers'
  get 'social-prescribers', to: 'pages#social_prescribers'
  get 'culture-tourism', to: 'pages#culture_tourism'

  scope module: :admin, as: :admin, constraints: { subdomain: 'admin' } do
    resources :articles
    resources :calendars do
      member do
        post :import
      end
    end
    resources :collections
    resources :neighbourhoods
    resources :partners do
      collection do
        get :lookup_name
      end
      member do
        delete :clear_address
      end
    end
    resources :tags
    resources :sites
    resources :supporters
    resources :users do
      member do
        patch :update_profile
      end
    end
    get 'profile' => 'users#profile', as: :profile
    get 'jobs' => 'jobs#index', as: :jobs

    root 'pages#home'
  end

  constraints(Sites::Local) do
    get '/' => 'sites#index'
  end

  root 'pages#home'

  ymd = { year: /\d{4}/,
          month: /\d{1,2}/,
          day: /\d{1,2}/ }

  # Events
  resources :events, only: %i[index show]
  get '/events/:year/:month/:day' => 'events#index', constraints: ymd, as: :events_by_date

  # Partners
  resources :partners, only: %i[index show]
  get '/partners/:id/events' => 'partners#show'
  get '/partners/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places' => 'partners#index' # Removing separate Places view for now.
  get '/partners/:id/embed' => 'places#embed'

  # news
  resources :news, only: %i[index show]

  # Legacy routes from when some Partners were Places. Don't let Google down...
  get '/places/:id' => 'partners#show'
  get '/places/:id/events' => 'partners#show'
  get '/places/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places/:id/embed' => 'places#embed'

  # Collections
  resources :collections, only: %i[show]

  # Named routes
  get 'winter2017', to: 'collections#show', id: 1
  get 'winter2018', to: 'collections#show', id: 2

  get '/robots.txt' => 'pages#robots'

  post '/api/v1/graphql', to: 'graphql#execute'

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/api/v1/graphql' if Rails.env.development?
end

app/controllers/admin/jobs_controller.rb
# frozen_string_literal: true

module Admin
  class JobsController < Admin::ApplicationController
    before_action :must_have_root_user

    def index
      @job_count = ActiveRecord::Base
                   .connection.execute('select count(*) from delayed_jobs')
                   .first['count']

      @calendar_counts = Calendar.group(:calendar_state).count

      @error_calendars = Calendar.where(calendar_state: 'error')
      @busy_calendars = Calendar.where(calendar_state: 'in_worker')
      # @bad_source_calendars = Calendar.where(calendar_state: 'bad_source')
    end

    private

    def must_have_root_user
      return if current_user.root?

      redirect_to root_path
    end
  end
end

app/views/admin/jobs/_calendar_row.html.erb
<table class="table table-bordered table-hover table-sm">
  <tr>
    <th>ID</th>
    <td><%= cal.id -%></td>
  </tr>
  <tr>
    <th>partner</th>
    <td>(<%= cal.partner_id -%>) <%= link_to cal.partner.name, admin_partner_path(cal) -%></td>
  </tr>
  <tr>
    <th>events</th>
    <td><%= cal.events.count -%></td>
  </tr>
  
  <tr>
    <th>source</th>
    <td><%= link_to cal.source, cal.source -%></td>
  </tr>
  <tr>
    <th>strategy</th>
    <td>"<%= cal.strategy -%>"</td>
  </tr>
  <tr>
    <th>importer_mode</th>
    <td>"<%= cal.importer_mode -%>"</td>
  </tr>

  <tr>
    <th>calendar_state</th>
    <td>"<%= cal.calendar_state -%>"</td>
  </tr>
  <tr>
    <th>importer_used</th>
    <td>"<%= cal.importer_used -%>"</td>
  </tr>
  <tr>	   
    <th>last_import_at</th>
    <td>"<%= cal.last_import_at -%>"</td>
  </tr>
  <tr>
    <th>critical_error</th>
    <td>"<%= cal.critical_error -%>"</td>
  </tr>
</table>

app/views/admin/jobs/index.html.erb
<h1>Calendar Importer Status</h1>

<p>Currently have <%= @job_count %> jobs</p>

<% states = Calendar::ALLOWED_STATES -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th>State</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <% states.each do |state_name| -%>
      <tr>
        <td><%= state_name %></td>
        <td><%= @calendar_counts[state_name.to_s] || 0 %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

<% if @error_calendars.count > 0 -%>
<h2><%= @error_calendars.count %> Error Calendars</h2>
<% @error_calendars.order(:name).each do |cal| -%>
  <h3><%= link_to cal.name, edit_admin_calendar_path(cal) -%></h3>
  <%= render 'calendar_row', cal: cal %>
  <br>
<% end -%>
<% end -%>

<% if @busy_calendars.count > 0 -%>
<h2><%= @busy_calendars.count %> Busy Calendars</h2>
<% @busy_calendars.order(:name).each do |cal| -%>
  <h3><%= link_to cal.name, edit_admin_calendar_path(cal) -%></h3>
  <%= render 'calendar_row', cal: cal %>
<br>
<% end -%>
<% end -%>

<!-- pre>
<% #= JSON.pretty_generate(@calendar_counts) %>
</pre -->