config/routes.rb
# frozen_string_literal: true

# config/routes.rb
Rails.application.routes.draw do
  # User login stuff
  devise_for :users,
             controllers: {
               invitations: 'users/invitations',
               sessions: 'users/sessions',
               passwords: 'users/passwords'
             }

  # Static pages
  get 'get-in-touch', to: 'joins#new'
  post 'get-in-touch', to: 'joins#create'
  get 'privacy', to: 'pages#privacy'
  get 'find-placecal', to: 'pages#find_placecal'
  get 'our-story', to: 'pages#our_story'
  get 'terms-of-use', to: 'pages#terms_of_use'

  get 'community-groups', to: 'pages#community_groups'
  get 'metropolitan-areas', to: 'pages#metropolitan_areas'
  get 'vcses', to: 'pages#vcses'
  get 'housing-providers', to: 'pages#housing_providers'
  get 'social-prescribers', to: 'pages#social_prescribers'
  get 'culture-tourism', to: 'pages#culture_tourism'

  scope module: :admin, as: :admin, constraints: { subdomain: 'admin' } do
    resources :articles
    resources :calendars do
      member do
        post :import
      end
    end
    resources :collections
    resources :neighbourhoods
    resources :partners do
      collection do
        get :lookup_name
      end
      member do
        delete :clear_address
      end
    end
    resources :tags
    resources :sites
    resources :supporters
    resources :users do
      member do
        patch :update_profile
      end
    end
    get 'profile' => 'users#profile', as: :profile
    get 'jobs' => 'jobs#index', as: :jobs

    root 'pages#home'
  end

  constraints(Sites::Local) do
    get '/' => 'sites#index'
  end

  root 'pages#home'

  ymd = { year: /\d{4}/,
          month: /\d{1,2}/,
          day: /\d{1,2}/ }

  # Events
  resources :events, only: %i[index show]
  get '/events/:year/:month/:day' => 'events#index', constraints: ymd, as: :events_by_date

  # Partners
  resources :partners, only: %i[index show]
  get '/partners/:id/events' => 'partners#show'
  get '/partners/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places' => 'partners#index' # Removing separate Places view for now.
  get '/partners/:id/embed' => 'places#embed'

  # news
  resources :news, only: %i[index show]

  # Legacy routes from when some Partners were Places. Don't let Google down...
  get '/places/:id' => 'partners#show'
  get '/places/:id/events' => 'partners#show'
  get '/places/:id/events/:year/:month/:day' => 'partners#show', constraints: ymd
  get '/places/:id/embed' => 'places#embed'

  # Collections
  resources :collections, only: %i[show]

  # Named routes
  get 'winter2017', to: 'collections#show', id: 1
  get 'winter2018', to: 'collections#show', id: 2

  get '/robots.txt' => 'pages#robots'

  post '/api/v1/graphql', to: 'graphql#execute'

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/api/v1/graphql' if Rails.env.development?
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: %i[edit update destroy]
    before_action :set_user_partners_controller, only: %i[new edit create]
    before_action :validate_partner_relation, only: %i[create]

    def profile
      authorize current_user, :profile?
    end

    def update_profile
      authorize current_user, :update_profile?

      if update_user_profile
        bypass_sign_in(current_user)
        flash[:success] = 'User profile has been updated'
        redirect_to admin_profile_path

      else
        flash.now[:danger] = 'User profile was not updated'
        render 'profile', status: :unprocessable_entity
      end
    end

    def index
      @users = policy_scope(User).order({ updated_at: :desc }, :last_name, :first_name)
      authorize current_user

      respond_to do |format|
        format.html
        format.json do
          render json: UserDatatable.new(
            params,
            view_context: view_context,
            users: @users.includes(:neighbourhoods, :tags, :partners)
          )
        end
      end
    end

    def new
      @partners = collect_partners

      @user = User.new
      authorize @user
    end

    def edit
      @partners = collect_partners

      authorize @user
    end

    def update
      authorize @user

      if @user.update(permitted_attributes(@user))
        flash[:success] = 'User has been saved'
        redirect_to admin_users_path

      else
        flash.now[:danger] = 'User was not saved'
        render 'edit', status: :unprocessable_entity
      end
    end

    def create
      @user = User.new(permitted_attributes(User))

      authorize @user

      @user.skip_password_validation = true

      if @user.valid?
        @user.invite!
        flash[:success] = 'User has been created! An invite has been sent'
        redirect_to admin_users_path
      else
        @partners = collect_partners
        flash.now[:danger] = 'User was not created'
        render 'new', status: :unprocessable_entity
      end
    end

    def destroy
      authorize @user
      @user.destroy
      respond_to do |format|
        format.html do
          flash[:success] = 'User has been deleted successfully'
          redirect_to admin_users_url
        end

        format.json { head :no_content }
      end
    end

    private

    def set_user_partners_controller
      @user_partners_controller =
        if current_user.root?
          'select2'
        else
          'user-partners'
        end
    end

    def collect_partners
      return policy_scope(Partner).where(id: params[:partner_id])&.map(&:id) if params[:partner_id]

      @user&.partners&.map(&:id)
    end

    def profile_params
      params.require(:user).permit(:first_name,
                                   :last_name,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :current_password,
                                   :phone,
                                   :avatar)
    end

    def update_user_profile
      if profile_params[:current_password].present? ||
         profile_params[:password].present? ||
         profile_params[:password_confirmation].present?

        current_user.update_with_password(profile_params)
      else
        current_user.update_without_password(profile_params)
      end
    end

    def validate_partner_relation
      # we only allow admins to assign partners they can see so any ids here are proof of a relationship
      return if current_user.root?
      return unless params[:user][:partner_ids].reject { |id| id == '' }.empty?

      # we're about to refresh the page so save the users input
      @user = User.new(permitted_attributes(User))
      flash.now[:danger] = 'User was not created: You must assign a Partner to the User or you will not be able to access it after creation'
      render 'new', status: :unprocessable_entity
    end
  end
end

app/controllers/users/auth_common.rb
# frozen_string_literal: true

class DeviseController
  # monkey patching devise so it can handle the new default behaviour in rails 7
  #   redirects

  original_redirect_to = instance_method(:redirect_to)
  define_method(:redirect_to) do |options, response_options = {}|
    if options.is_a?(Hash)
      options[:allow_other_host] = true unless options.key?(:allow_other_host)

    elsif response_options.is_a?(Hash)
      response_options[:allow_other_host] = true unless response_options.key?(:allow_other_host)
    end

    original_redirect_to
      .bind_call(self, options, response_options)
  end
end

module Users
  module AuthCommon
    def self.included(klass)
      klass.before_action :devise_check_on_root_site
      klass.after_action :patch_flash
    end

    private

    # action filter:
    #
    # In devise controllers: push all users on any subdomain of placecal to
    #   authenticate on the base placecal.org site so the site is set up
    #   properly and the styling will work
    #
    def devise_check_on_root_site
      return if current_user.present?
      return if request.subdomain.blank?

      redirect_to url_for(subdomain: nil)
    end

    def patch_flash
      # notice -> success
      # alert -> danger
      if flash.key?(:notice)
        flash[:success] = flash[:notice]
        flash.delete :notice
      end

      if flash.key?(:alert)
        flash[:danger] = flash[:alert]
        flash.delete :alert
      end

      if flash.now.flash.key?(:notice)
        flash.now[:success] = flash.now[:notice]
        flash.now.flash.delete :notice
      end

      if flash.now.flash.key?(:alert)
        flash.now[:danger] = flash.now[:alert]
        flash.now.flash.delete :alert
      end
    end

    # when we logging the user in- take them to the admin site
    #
    # == Parameters
    #   resource_or_scope: ignored
    #
    # == Returns
    #   URL of admin site with correct path and subdomain
    def after_sign_in_path_for(_resource_or_scope)
      route_for(
        :root,
        subdomain: Site::ADMIN_SUBDOMAIN
      )
    end

    # used by password set/reset
    #
    # == Parameters
    #   resource_or_scope: ignored
    #
    # == Returns
    #   full url with domain to take user to
    def after_accept_path_for(_resource_or_scope)
      route_for(
        :root,
        subdomain: Site::ADMIN_SUBDOMAIN
      )
    end

    # the path to redirect to the user to when sign out happens
    #
    # == Parameters
    #   resource_or_scope: ignored
    #
    # == Returns
    #   full url with domain to take user to
    def after_sign_out_path_for(_resource_or_scope)
      route_for(
        :root,
        subdomain: nil
      )
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

require_relative "auth_common"

class Users::ConfirmationsController < Devise::ConfirmationsController
  include Users::AuthCommon
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

require_relative "auth_common"

class Users::InvitationsController < Devise::InvitationsController
  include Users::AuthCommon

  before_action :set_site
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

require_relative 'auth_common'

class Users::PasswordsController < Devise::PasswordsController
  include Users::AuthCommon

  before_action :set_site

  # POST /resource/password
  def create
    resource_class.send_reset_password_instructions(resource_params)

    redirect_to new_user_password_path, notice: 'If a PlaceCal account is associated with the submitted email address, password reset instructions have been sent.'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

require_relative 'auth_common'

class Users::SessionsController < Devise::SessionsController
  include Users::AuthCommon

  before_action :set_site
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 240)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,
              alt: "A photo of #{user.full_name}",
              class: 'gravatar')
  end

  def options_for_roles
    User.role.values
  end

  def user_has_no_rights?(user)
    return false if user.root?
    return false if user.editor?
    return false if user.partnership_admin?
    return false if user.neighbourhood_admin?
    return false if user.partner_admin?

    true # they have no rights
  end

  def options_for_partners(user = nil)
    options = policy_scope(Partner).all.order(:name).pluck(:name, :id)
    return options unless user

    (options + user&.partners&.pluck(:name, :id)).uniq
  end

  def permitted_options_for_partners
    policy_scope(Partner).all.pluck(:id)
  end

  def options_for_user_neighbourhoods(for_user)
    legacy_neighbourhoods = for_user.neighbourhoods.where.not(release_date: Neighbourhood::LATEST_RELEASE_DATE)

    scope = Neighbourhood.find_latest_neighbourhoods_maybe_with_legacy_neighbourhoods(policy_scope(Neighbourhood), legacy_neighbourhoods)

    scope
      .order(:name)
      .all
      .collect do |ward|
        if ward.legacy_neighbourhood?
          ["#{ward.contextual_name} - #{ward.release_date.year}/#{ward.release_date.month}", ward.id]
        else
          [ward.contextual_name, ward.id]
        end
      end
  end

  def role_label(value)
    case value.second
    when 'root'
      '<strong>Root</strong>: Can do everything'.html_safe
    when 'editor'
      '<strong>Editor</strong>: Can edit news articles'.html_safe
    when 'citizen'
      '<strong>Citizen</strong>: ' \
      'Can only edit entities listed on this page'.html_safe
    else
      value
    end
  end
end

app/views/admin/users/_contact.html.erb
<div class="row">
  <div class="col-md-6">
    <%= f.input :first_name %>
  </div>
  <div class="col-md-6">
    <%= f.input :last_name %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= f.input :email %>
  </div>
  <div class="col-md-6">
    <%= f.input :phone %>
  </div>
</div>

<%= f.input :avatar,
  hint: image_uploader_hint(f.object.avatar)  %>

<%= image_tag f.object.avatar.retina.url if f.object.avatar.retina.url %>

app/views/admin/users/_form.html.erb
<%= render_component "error", object: f.object %>

<div class="form-group">
  <%= render "contact", f: f %>

  <br>
  <hr>

  <div class="row">
    <div class="col-md-6">
      <h3>Partners</h3>
      <p>Partners this user can edit, as well as their associated calendars</p>
      <%= f.association :partners,
                        label: false,
                        collection: options_for_partners(params[:id] ? User.find(params[:id]) : nil),
                        selected: @partners || @user.partners.pluck(:id),
                        input_html: { 
                          class: 'form-control',
                          data: { 
                            controller: @user_partners_controller, 
                            "user-partners-permitted-partners-value": permitted_options_for_partners
                          } 
                        } %>
    </div>

    <div class="col-md-6">
      <h3>Neighbourhoods</h3>

      <% if current_user.root? %>
        <p>Grants access to every partner and calendar in these neighbourhoods. Use with care!</p>

        <%= f.association :neighbourhoods,
          label: false,
          collection: options_for_user_neighbourhoods(f.object),
          input_html: { class: 'form-control', data: { controller: "select2" } } %>

      <% else %>
        <ul class='neighbourhood-list'>
          <% @user.neighbourhoods.order(:name).each do |hood| -%>
            <li><%= link_to hood.name, admin_neighbourhood_path(hood) %></li>
          <% end -%>
        </ul>
      <% end %>

    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3>Partnerships</h3>
      <p>Grants access to add or remove partners from partnerships</p>
      <%= f.association :tags,
                        label: false,
                        collection: options_for_tags,
                        input_html: { class: 'form-control', data: { controller: "select2" } } %>
    </div>
    <div class="col-md-6">
      <h3>Role</h3>
      <%= f.input :role,
                  as: :radio_buttons,
                  label_method: ->(val){ role_label(val) } %>
    </div>
  </div>

  <br>
  <hr>

</div>

app/views/admin/users/edit.html.erb
<h1 class="page-header">Edit User: <%= @user.full_name %></h1>

<%- disabled_fields = policy(@user).disabled_attributes_for_update %>
<%- displayable_fields = policy(@user).permitted_attributes_for_update %>

<%=  filtered_form_for(@user,
                       method: :put,
                       url: admin_user_path(@user),
                       disabled: disabled_fields,
                       display_only: displayable_fields) do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "Update", class: "btn btn-primary " %>
  <% if policy(@user).destroy? && !@user.site_admin? -%>
    <%= link_to "Delete user", 
      admin_user_path(@user), 
      method: :delete, 
      class: "btn btn-danger", 
      data: { confirm: "Please confirm you want to delete this user.\n\nThis is permanent!" } %>
  <% end -%>
<% end %>

app/views/admin/users/index.html.erb
<script>
var columns = [
    {"data": "id"},
    {"data": "first_name"},
    {"data": "last_name"},
    {"data": "admin_roles"},
    {"data": "email"},
    {"data": "updated_at"}
  ]
</script>

<%= render partial: "layouts/admin/datatable", locals: {
    title: "Users",
    model: :users,
    column_titles: ['ID', 'First name', 'Last name', 'Roles', 'Email', 'Last updated'],
    columns: %i[id first_name last_name admin_roles email updated_at],
    data: @users,
    source: admin_users_path(format: :json),
    new_link: new_admin_user_path
  }
%>

app/views/admin/users/new.html.erb
<% content_for :title do %>New User<% end %>

<h1 class="page-header">New User</h1>

<%- display_fields = policy(@current_user).permitted_attributes_for_create %>

<%= filtered_form_for([:admin, @user],
                      display_only: display_fields) do |f| %>
  <%= render 'form', f: f %>
  
  <p>
    Please note: inviting a user will require their acceptance of the PlaceCal <%= link_to 'Terms of Use', terms_of_use_path %>.
  </p>

  <%= f.submit "Invite", class: "btn btn-primary " %>
<% end %>

app/views/admin/users/profile.html.erb
<h1 class="page-header">Edit Profile</h1>

<% if current_user.root? -%>
  <p>To modify neighbourhoods, tags and partners go to the <%= link_to 'user edit page', edit_admin_user_path(current_user) %>.</p>
<% end -%>

<%= simple_form_for current_user, as: :user, method: :patch, url: update_profile_admin_user_path(current_user), html: { class: "form-horizontal" } do |f| %>
  <div class="row mt-4">
    <%= render_component "error", object: current_user %>
    <div class="col-md-12">
      <h2>Basic information</h2>
      <%= render "contact", f: f %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">
      <h2>Password</h2>
      <p>Leave this blank if you don't want to change your password.</p>
      <%= f.input :password, autocomplete: "off" %>
      <% if @minimum_password_length %>
        <br>
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
      <%= f.input :password_confirmation, autocomplete: "off" %>

      <%= f.input :current_password, autocomplete: "off", hint: 'Enter your current password if you want to change it' %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-12">
      <h2>Admin rights</h2>
      <% if current_user.root? %>
        <div class="profile__is-root">
          <p>You are a <strong>root</strong> user and can do everything! be careful!</p>
        </div>
      <% else %>
        <% if user_has_no_rights?(current_user) -%>
          <p class='has-no-admin-rights-warning'>You have no admin rights. This probably means someone didn't set up your account correctly - please ask whoever invited you!</p>
        <% end -%>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <% if current_user.partners.any? %>
        <h3>Your partners</h3>
        <ul>
          <% current_user.partners.each do |partner| %>
            <li>
              <%= link_to partner.name, edit_admin_partner_path(partner) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="col-md-6">
      <% if current_user.neighbourhoods.any? %>
        <h3>Your neighbourhoods</h3>
        <ul>
          <% current_user.neighbourhoods.each do |neighbourhood| %>
            <li>
              <%= link_to neighbourhood.contextual_name, edit_admin_neighbourhood_path(neighbourhood) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <% if current_user.partnership_admin? %>
        <h3>Your assigned tags</h3>
        <p>Please note these tags will be pre-selected when creating a new partner<p>
        <ul>
          <% current_user.tags.each do |tag| %>
            <li>
              <%= link_to tag.name, edit_admin_tag_path(tag) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <br><br>
  <%= f.submit "Update", class: "btn btn-primary " %>
<% end %>